Update infrastructure-as-code.yml

diff --git a/.github/workflows/infrastructure-as-code.yml b/.github/workflows/infrastructure-as-code.yml
--- a/.github/workflows/infrastructure-as-code.yml
+++ b/.github/workflows/infrastructure-as-code.yml
@@ -1,4 +1,5 @@
-name: Infrastructure as Code
+name: Infrastructure as Code Security Scan
+
 on:
   issues:
     types: [opened]
@@ -12,11 +13,12 @@ on:
         description: 'Fail on security level (e.g., high, medium)'
         required: false
         type: string
+        default: ''
       PATH:
         description: 'Path to the file or directory to scan'
         required: true
         type: string
-        default: "./"
+        default: './'
 
 jobs:
   infrastructure-as-code:
@@ -32,20 +34,29 @@ jobs:
     steps:
       - name: Checkout Source Code
         uses: actions/checkout@v4
-          
+
       - name: Generate results-dir
         run: mkdir -p results-dir
 
       - name: Run KICS Scan
         uses: Checkmarx/kics-github-action@v1.7.0
         with:
-          path: ${{ inputs.PATH }}
-          fail_on: ${{ inputs.FAIL_ON }}
+          path: ${{ inputs.PATH || './' }}
+          fail_on: ${{ inputs.FAIL_ON || '' }}
           output_path: results-dir
-          output_formats: 'json,sarif'
+          output_formats: 'sarif'
 
       - name: Upload SARIF file
         if: always()
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: results-dir/results.sarif
+
+      - name: Check SARIF Output
+        if: always()
+        run: |
+          if [ -f results-dir/results.sarif ]; then
+            echo "SARIF file generated successfully."
+          else
+            echo "SARIF file not found!"
+            exit 1
